server:
  port: 9005

spring:
  datasource:
    url: jdbc:mysql://81.70.71.16:3306/kila_kila_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cba123456cba
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    password: cba123456cba
    host: 81.70.71.16
    port: 6379

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/kila_kila_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
#    username: root
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  servlet:
#    multipart:
#      max-file-size: 2MB
#      max-request-size: 5MB
#  redis:
#    password:
#    host: localhost
#    port: 6379

mybatis-plus:
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false
