server:
  port: 9004

spring:
  datasource:
    url: jdbc:mysql://101.37.117.226:3333/kila_kila_blog?characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: cba123456cba
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB
  redis:
    password: cba123456cba
    host: 101.37.117.226
    port: 6379

mybatis-plus:
  # configuration:
  #   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
    banner: false